<?php /* Smarty version 2.6.0, created on 2009-03-26 16:00:15
         compiled from blank.tpl */ ?>
<html>
<head>
	<title><?php echo $this->_tpl_vars['maintitle']; ?>
</title>
			<link rel="stylesheet" href="<?php echo $this->_tpl_vars['subdir']; ?>
media/stylesheet.css" />
			<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
</head>
<body>
<div align="center"><h1><?php echo $this->_tpl_vars['maintitle']; ?>
</h1></div>
<b>Welcome to <?php echo $this->_tpl_vars['package']; ?>
!</b><br />
<br />
This documentation was generated by <a href="<?php echo $this->_tpl_vars['phpdocwebsite']; ?>
">phpDocumentor v<?php echo $this->_tpl_vars['phpdocversion']; ?>
</a><br />
</body>
</html>